### ISSUE TITLE
[WEB] Mute chat is not working properly

### ISSUE THREAD

**Issue by nqhhdev** [linagora/twake-on-matrix#1504]
OS: WEB
Device: Chrome 
Twake Chat version: 2.4.18

*Reproduce Step:

Mute a chat in chat list

Actual:
- Still received notifications related to old messages

Expected:
- Cannot receive notification

![Image](https://github.com/linagora/twake-on-matrix/assets/99852347/f07e503c-4ea9-4446-8ed5-2562a1e49100)

**Comment by nqhhdev** [comment]
![Image](https://github.com/linagora/twake-on-matrix/assets/99852347/15107029-b28f-4b4b-8087-d02520a8ff08)

**Comment by Te-Z** [comment]
I was not able to reproduce the bug because of a problem on matrix.tom-dev.xyz


[Capture vidéo du 07-03-2024 16:24:50.webm](https://github.com/linagora/twake-on-matrix/assets/31937920/7f551e2e-391e-4cc6-8f98-67970f5b7a0a)


![Capture d’écran du 2024-03-07 16-31-34](https://github.com/linagora/twake-on-matrix/assets/31937920/a4ad4db4-f6a2-4154-8e61-643c5d542b34)

**Comment by Te-Z** [comment]
Okay I finally found a way to reproduce the bug.

Looks like if you haven't already open the chat after opening the app you still have the notifications. But if you open it and then change of room, it works as expected.

[Capture vidéo du 07-03-2024 17:38:34.webm](https://github.com/linagora/twake-on-matrix/assets/31937920/4dd21491-0953-4223-b390-fbb89133686a)

**Comment by Te-Z** [comment]
@nqhhdev Reproduce steps:

- User A mute room X
- User A enter the chat room
- Go in an other room
- User B send a message in room X
- User A still got a notification
