### ISSUE TITLE
[Bug] [MOBILE] Cannot attach a file

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1543]
iOS, 2.4.19 

1. Go to a chat 
2. Select attach a file
3. Try attaching a file 
4. Nothing happens 

https://github.com/linagora/twake-on-matrix/assets/97684890/b1dc9667-4330-4e02-a55c-862f884286c6

**Comment by hoangdat** [comment]
@sherlockvn please grooming it also

**Comment by sherlockvn** [comment]
### DESC:
- Because the file is on the cloud, so it need to be downloaded first before add to our files. In this case we can improve the process of picking the cloud file. We should make the same picking process as the telegram does: 
- Separate the files which is in the device
- When picking a file from icloud, make user waiting for downloading the file first
### Reference:

https://github.com/linagora/twake-on-matrix/assets/43041967/dc6dac74-7f2b-4d35-8006-5ac1baa29620

### DOD:
- [ ] Separate the files which is in the device
- [ ] wait for downloading the file first before picking the file

**Comment by QuangHoang1210** [comment]
**Passed on IOS 2.5.0** 

https://github.com/linagora/twake-on-matrix/assets/124866146/fcc34b82-6900-476c-a8b8-c95dbc52ddcd
