### ISSUE TITLE
Can not send image when no other one join in room

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#182]
### Desc:
- create a chat or a dialog 
- go to the chat 
- send an image 
- error

### DoD:
- what is the problem?
- how to send it success?

**Comment by hoangdat** [comment]
matrix.linagora.com

**Comment by imGok** [comment]
couldn't reproduce it in matrix.org, matrix.linagora.com



![Image](https://github.com/linagora/twake-on-matrix/assets/48354990/41cbe459-9892-4a4f-9a72-34cce38409fe)

**Comment by imGok** [comment]
Maybe it's iOS bug ?

**Comment by hoangdat** [comment]
please create a group with me (@laisam:matrix.org). and then send a image

**Comment by imGok** [comment]
I managed to get the error (https://developer.mozilla.org/fr/docs/Web/HTTP/Status/413) - Payload too large. But I don't get the error everytime even if I send the same picture

**Comment by imGok** [comment]
![Image](https://github.com/linagora/twake-on-matrix/assets/48354990/9da2d87c-c208-43f8-a3e0-8951f3481ac1)



![Image](https://github.com/linagora/twake-on-matrix/assets/48354990/b53f387d-a213-4ee1-9981-0e4d8409a1b7)

**Comment by imGok** [comment]
Solution : check the file size before sending it

**Comment by imGok** [comment]
Format error when sending the image, do not happen everytime

![image](https://github.com/linagora/twake-on-matrix/assets/48354990/930be000-a36d-421f-8916-20d03b79237b)

**Comment by imGok** [comment]
I tried 2 pictures, large and small : 

Large picture (not working) : 
Error : 413 - Request Entity Too Large
(L93 - uploadContent() - room.extension.dart)

This shouldn't happen because mUploadSize = 104 857 600 and this file = 10 995 681
We check in the code if the file is too big before sending it

![Image](https://github.com/linagora/twake-on-matrix/assets/48354990/feca93c9-d5be-49d4-ae13-1302c6d45293)

Small picture (working) : 
![Image](https://github.com/linagora/twake-on-matrix/assets/48354990/653d8b3b-063a-4461-80a3-310d128a434d)

**Comment by imGok** [comment]
Sending too large picture
![Image](https://github.com/linagora/twake-on-matrix/assets/48354990/de200c82-8af7-4a99-abe2-6237cc7fd85b)

**Comment by hoangdat** [comment]
the same with big jpeg
