### ISSUE TITLE
Error when sending big JPEG images

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#197]
Happend when not shrink the image down and JPEG image file
- Log: FormatException: Unexpected character (at character 1)

**Comment by hoangdat** [comment]
What is the limitation of acceptable image?

**Comment by hoangdat** [comment]
What is the best UX for user about the limitation? what is the next step?

**Comment by imGok** [comment]
@hoangdat After some tests on matrix.linagora.com and matrix.org
both servers have same max file size upload : 104 857 600 bytes

**matrix.linagora.com**

Success : send the big picture (11MB) in a group / room 
![Image](https://github.com/linagora/twake-on-matrix/assets/48354990/8f9e32fc-a4f5-4ddb-863b-478b4f9beb89)

Fail : send the big picture in a private chat (user to user) - 413 error 
![Image](https://github.com/linagora/twake-on-matrix/assets/48354990/2586bb54-1e81-4e3b-87cf-57520f0ebf57)

**matrix.org**

Success : send the big picture (11MB) in a group / room 
![Image](https://github.com/linagora/twake-on-matrix/assets/48354990/5031d1bb-7b73-45db-af82-8eef44644e95)

Success : send the big picture in a private chat (user to user)
![Image](https://github.com/linagora/twake-on-matrix/assets/48354990/b5a278b7-573a-458c-be53-793d63c82ea4)

Conclusion : 

We cannot send big JPEG in a private chat because the mimeType is not an octet-stream

**Comment by hoangdat** [comment]
Related to max file size configuration
