### ISSUE TITLE
[M1] What happen if user typing+ sending very fast a lot of message

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#275]
### Desc:

https://user-images.githubusercontent.com/6462404/251004924-b7cab38e-8bec-447e-8590-ebf64006fc89.mp4

### DoD:
- [ ] What happen with it
- [ ] How to fix

**Comment by sherlockvn** [comment]
The problem is there are too many request in the short interval time
`
I/flutter ( 4293): [Matrix] Problem while sending message - M_LIMIT_EXCEEDED: Too Many Requests
I/flutter ( 4293): #0      MatrixApi.unexpectedResponse
matrix_api.dart:52
I/flutter ( 4293): #1      Api.sendMessage
api.dart:3433
I/flutter ( 4293): <asynchronous suspension>
I/flutter ( 4293): #2      Room._sendContent
room.dart:935
I/flutter ( 4293): <asynchronous suspension>
I/flutter ( 4293): #3      Room.sendEvent
room.dart:1063
I/flutter ( 4293): <asynchronous suspension>
I/flutter ( 4293): #4      CommandsClientExtension.registerDefaultCommands.<anonymous closure>
commands_extension.dart:83
I/flutter ( 4293): <asynchronous suspension>
I/flutter ( 4293): #5      CommandsClientExtension.parseAndRunCommand
commands_extension.dart:46
I/flutter ( 4293): <asynchronous suspension>
`

**Comment by hoangdat** [comment]
- what is the short interval time?
- How to get it?
