### ISSUE TITLE
[Feedback][Notification] Config the default push rule for all the chat

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#504]
```
1. I receive a message in DM 
2. I receive a message in group chat
3. I receive a message in thread (to be done)
4. Name of the group chat is changed
5. Avatar of the group chat is edited
6. I am assigned as admin
7. A video/phone call is started (to be done)
8. Someone left a reaction to my message (to be done)
9. Someone tag me in group chat
10. admin add me in chat
```

**Comment by sherlockvn** [comment]
### Current status: 
Because server-set rules are limited, some rules must be created by users, for that, we first need to create a rule, reference: https://spec.matrix.org/v1.7/client-server-api/#put_matrixclientv3pushrulesscopekindruleid, so you have to find the place in matrix dart SDK for setting default push rules. Then you can enable/disable push rules in notification settings.

### Current problem:
Where is the place to define default push rules ?

**Comment by hoangdat** [comment]
### get current push rule

### set push rule

**Comment by hoangdat** [comment]
```
1. I receive a message in DM 
2. I receive a message in group chat
```
Should be belonged to settings of each chat.

**Comment by hoangdat** [comment]
```
4. Name of the group chat is changed
5. Avatar of the group chat is edited
```
App settings

**Comment by hoangdat** [comment]
```
9. only receive noti when tagged
```
in chat settings
